spring:
  datasource:
    url: jdbc:postgresql://db:5432/meteo
    username: meteo
    password: meteo

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

meteo:
  polling:
    realtimeMs: 900000
  cache:
    maxAgeMinutes: 180
  rate-limit:
    permitsPerMinute: 6
  backoff:
    minutes: 30
  circuit-breaker:
    failureThreshold: 3
    waitOpenMinutes: 30
