apiVersion: v1
kind: ConfigMap
metadata:
  name: meteo-db-init
  namespace: group-6
data:
  init.sql: "CREATE EXTENSION IF NOT EXISTS timescaledb;\n\nCREATE TABLE IF NOT EXISTS\
    \ meteo_observation (\n  id BIGSERIAL PRIMARY KEY,\n  station_id TEXT,\n  station_name\
    \ TEXT,\n  city TEXT,\n  lat DOUBLE PRECISION,\n  lon DOUBLE PRECISION,\n  observed_at\
    \ TIMESTAMP NOT NULL,\n  temperature DOUBLE PRECISION,\n  relative_humidity DOUBLE\
    \ PRECISION,\n  pressure DOUBLE PRECISION,\n  raw_json TEXT\n);\n\nSELECT create_hypertable('meteo_observation',\
    \ 'observed_at', if_not_exists => TRUE);\n\nCREATE INDEX IF NOT EXISTS idx_meteo_station_time\
    \ ON meteo_observation (station_id, observed_at DESC);\nCREATE INDEX IF NOT EXISTS\
    \ idx_meteo_city ON meteo_observation (city);\n"
