apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: group-6
data:
  datasources/datasource.yml: "apiVersion: 1\ndatasources:\n  - name: TimescaleDB\n\
    \    type: postgres\n    access: proxy\n    url: db:5432\n    database: meteo\n\
    \    user: meteo\n    secureJsonData:\n      password: meteo\n    jsonData:\n\
    \      sslmode: \"disable\"\n      postgresVersion: 1400\n      timescaledb: true\n"
  dashboards/dashboard.yml: "apiVersion: 1\nproviders:\n  - name: 'default'\n    orgId:\
    \ 1\n    folder: ''\n    type: file\n    disableDeletion: false\n    editable:\
    \ true\n    options:\n      path: /etc/grafana/provisioning/dashboards\n"
