apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: group-6
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: mgmt
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - rabbitmq-diagnostics -q ping
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - rabbitmq-diagnostics -q ping
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: csi-cinder-fast
      resources:
        requests:
          storage: 5Gi
