spring:
  datasource:
    url: jdbc:postgresql://db:5432/meteo
    username: meteo
    password: meteo

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

meteo:
  polling:
    realtimeMs: 300000
