apiVersion: v2
name: redis
description: Redis caching service for MeteoPiemonte.
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - meteopiemonte
  - redis
  - cache
maintainers:
  - name: alessandroscalise
