apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: db:5432
    database: meteo
    user: meteo
    secureJsonData:
      password: meteo
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: true
