apiVersion: v1
kind: Service
metadata:
  name: {{ include "analysis-service.fullname" . }}
spec:
  selector:
    app: {{ include "analysis-service.fullname" . }}
  ports:
  - port: 8000
    targetPort: 8000
    name: http
