apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rabbitmq.fullname" . }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: amqp
              containerPort: 5672
            - name: mgmt
              containerPort: 15672
          envFrom:
            - secretRef:
                name: {{ include "rabbitmq.fullname" . }}-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 90 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storage.className | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}
