apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ required "auth.username is required" .Values.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ required "auth.password is required" .Values.auth.password | quote }}
