apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin-secret
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ required "auth.adminUser is required" .Values.auth.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ required "auth.adminPassword is required" .Values.auth.adminPassword | quote }}
