apiVersion: v1
kind: Service
metadata:
  name: '{{ include "grafana.fullname" . }}'
spec:
  selector:
    app: '{{ include "grafana.fullname" . }}'
  ports:
  - port: 3000
    targetPort: 3000
    name: http
