apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ include "grafana.fullname" . }}-admin-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
              subPath: dashboard.yml
              readOnly: true
            - name: provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-data
        - name: provisioning-dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-provisioning
        - name: provisioning-datasources
          configMap:
            name: {{ include "grafana.fullname" . }}-provisioning
