apiVersion: v1
kind: Service
metadata:
  name: '{{ include "meteo-core.fullname" . }}'
spec:
  selector:
    app: '{{ include "meteo-core.fullname" . }}'
  ports:
  - port: 8080
    targetPort: 8080
    name: http
