apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: meteopiemonte
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: umbrella
            path: 04-kubernetes/meteopiemonte
  template:
    metadata:
      name: "meteopiemonte-{{name}}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: meteopiemonte
        app.kubernetes.io/managed-by: argocd
    spec:
      project: alessandro
      source:
        repoURL: https://github.com/scalisesufa-tech/MeteoPiemonte.git
        targetRevision: iac
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: group-6
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
