apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: meteopiemonte-microservices
  namespace: argocd
spec:
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/scalisesufa-tech/MeteoPiemonte.git
        revision: iac
        directories:
          - path: "04-kubernetes"
  template:
    metadata:
      name: "meteopiemonte-{{path.basename}}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: meteopiemonte
        app.kubernetes.io/managed-by: argocd
    spec:
      # Correzione: progetto impostato su "alessandro"
      project: alessandro
      source:
        repoURL: https://github.com/scalisesufa-tech/MeteoPiemonte.git
        targetRevision: iac
        path: "{{path}}"
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: group-6
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
