apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  selector:
    app: {{ include "frontend.fullname" . }}
  ports:
  - port: 3000
    targetPort: 3000
    name: http
