apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meteo-db.fullname" . }}-secret
  labels:
    {{- include "meteo-db.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ required "auth.database is required" .Values.auth.database | quote }}
  POSTGRES_USER: {{ required "auth.username is required" .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ required "auth.password is required" .Values.auth.password | quote }}
