apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meteo-db
  namespace: group-6
  labels:
    app: meteo-db
spec:
  serviceName: meteo-db
  replicas: 1
  selector:
    matchLabels:
      app: meteo-db
  template:
    metadata:
      labels:
        app: meteo-db
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg14
        ports:
        - containerPort: 5432
          name: postgres
        envFrom:
        - secretRef:
            name: meteo-db-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          readOnly: true
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U $(POSTGRES_USER) -d $(POSTGRES_DB)
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: init
        configMap:
          name: meteo-db-init
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: csi-cinder-fast
      resources:
        requests:
          storage: 10Gi
