apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: group-6
  labels:
    app: grafana
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - secretRef:
            name: grafana-admin-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        - name: provisioning
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
          subPath: dashboard.yml
          readOnly: true
        - name: provisioning
          mountPath: /etc/grafana/provisioning/datasources/datasource.yml
          subPath: datasource.yml
          readOnly: true
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grafana-data
      - name: provisioning
        configMap:
          name: grafana-provisioning
