apiVersion: v2
name: meteo-core
description: Core backend service for MeteoPiemonte, handling data logic.
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - meteopiemonte
  - backend
  - java
maintainers:
  - name: alessandroscalise
