apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteo-core
  namespace: group-6
  labels:
    app: meteo-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meteo-core
  template:
    metadata:
      labels:
        app: meteo-core
    spec:
      containers:
      - name: meteo-core
        image: scalisufa/meteo-core:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: JAVA_TOOL_OPTIONS
          value: "-Djava.net.preferIPv4Stack=true"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://meteo-db:5432/meteo
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: meteo-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: meteo-db-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: org.hibernate.dialect.PostgreSQLDialect
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: '5672'
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 80
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
